services:
  db:
    image: postgres:16
    container_name: atmos-db
    restart: always
    environment:
      - POSTGRES_USER=atmos
      - POSTGRES_PASSWORD=atmospass
      - POSTGRES_DB=primesdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atmos -d primesdb"]
      interval: 5s
      timeout: 5s
      retries: 3

  vpn:
    # UPDATED: Using a stable legacy tag to fix macOS Docker routing bugs
    image: lscr.io/linuxserver/wireguard:v1.0.20210914-ls22
    container_name: atmos-vpn
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SERVERURL=192.168.178.39
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=1.1.1.1
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=10.13.13.0/24
    ports:
      - "51820:51820/udp"
      - "8000:8000"
    volumes:
      - ./config:/config
    restart: always

  app:
    build: .
    container_name: atmos-service
    network_mode: "service:vpn"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg://atmos:atmospass@atmos-db:5432/primesdb
    restart: always
