[Interface]
Address = 10.13.13.2
PrivateKey = 8LB2QwkL6p5hy9Rj3xl2FXQNZZB7QbRSK3SKcO/8yn4=
ListenPort = 51820
DNS = 1.1.1.1

[Peer]
PublicKey = X0D/Q+mT6foSXKEeVzIJl01GEINdYkGGhrtNgMBZuWo=
PresharedKey = n1nbtY0pJNSCL6PUmYtLNofuG6vGROt6X1nYluMsWKQ=
Endpoint = 192.168.178.39:51820
AllowedIPs = 10.13.13.0/24
