[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = eL7mR0XUPodrCrGBRFYslhPLRH/H00fozBZl6GbTd18=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = EBF5L0gCr/HDpVdIWxS1hETYI4NvmEd/FVO1VCqq5zw=
PresharedKey = n1nbtY0pJNSCL6PUmYtLNofuG6vGROt6X1nYluMsWKQ=
AllowedIPs = 10.13.13.2/32

